import { StyleSheet } from 'react-native';

import { appColors } from '../../../theme/colors';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#020617',
  },
  hiddenScreen: {
    display: 'none',
  },
  homeScreen: {
    flex: 1,
    backgroundColor: '#000000',
  },
  homeScroll: {
    flex: 1,
  },
  homeContent: {
    paddingHorizontal: 8,
    gap: 16,
  },
  homeHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
  },
  homeHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  homeAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#1e293b',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#334155',
  },
  homeAvatarText: {
    color: '#f8fafc',
    fontWeight: '700',
  },
  homeGreeting: {
    color: '#f8fafc',
    fontWeight: '700',
  },
  homeLocationBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  balanceCard: {
    borderWidth: 1,
    borderColor: 'rgba(204, 232, 226, 0.7)',
    borderRadius: 22,
    backgroundColor: '#010504',
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#6ee7d8',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    elevation: 3,
  },
  balanceColumn: {
    flex: 1,
    justifyContent: 'center',
    gap: 4,
  },
  balanceColumnLeft: {
    paddingRight: 12,
  },
  balanceColumnRight: {
    paddingLeft: 12,
  },
  balanceLabel: {
    color: '#f2f4f5',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '500',
    opacity: 0.78,
  },
  balanceValue: {
    color: '#f8fafc',
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '700',
    letterSpacing: -0.6,
  },
  balanceWalletRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  balanceCoinRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  balanceCoinUnit: {
    color: '#f8fafc',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    opacity: 0.8,
  },
  balanceDivider: {
    width: 1,
    alignSelf: 'stretch',
    marginVertical: 4,
    backgroundColor: 'rgba(236, 244, 242, 0.2)',
  },
  topUpChip: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#083f42',
    paddingHorizontal: 10,
    minHeight: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topUpChipText: {
    color: '#eefbf8',
    fontWeight: '700',
    fontSize: 10,
    lineHeight: 12,
  },
  balanceEyeWrap: {
    marginLeft: 10,
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  coinBadge: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#ffffff',
    borderStyle: 'dashed',
  },
  promoCarouselWrap: {
    gap: 10,
  },
  promoCarouselTrack: {
    alignItems: 'stretch',
  },
  promoSlide: {
    width: '100%',
    paddingHorizontal: 2,
  },
  welcomeBanner: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#0b3a36',
    flexDirection: 'row',
    minHeight: 126,
  },
  welcomeBody: {
    flex: 1,
    backgroundColor: '#f7f3eb',
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: 'space-between',
  },
  welcomeTitle: {
    color: '#0b0b0b',
    fontWeight: '800',
  },
  welcomeSubtitle: {
    color: '#454545',
    fontStyle: 'italic',
  },
  learnMoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  learnMoreText: {
    color: '#5f6a6a',
  },
  welcomeArt: {
    width: 112,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0a4a44',
  },
  welcomeCarFrame: {
    width: 68,
    height: 68,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#54d9b2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  bannerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#7f8685',
  },
  bannerDotActive: {
    width: 16,
    backgroundColor: '#f1f5f9',
  },
  servicesWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    // rowGap: 18,
    paddingHorizontal: 8,
    // paddingVertical: 8,
    // backgroundColor:'red'
  },
  serviceCard: {
    width: '45%',
    minHeight: 116,
    paddingHorizontal: 14,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    shadowColor: '#fff7ad',
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 6,
  },
  serviceCardLeft: {
    borderRadius: 46,
    transform: [{ rotate: '-9deg' }],
  },
  serviceCardRight: {
    borderRadius: 42,
    transform: [{ rotate: '8deg' }],
  },
  serviceCardCenter: {
    width: '50%',
    alignSelf: 'center',
    borderRadius: 36,
    transform: [{ rotate: '-5deg' }],
  },
  serviceCardSoft: {
    borderRadius: 40,
    transform: [{ rotate: '-8deg' }],
  },
  serviceTitle: {
    fontWeight: '800',
    textAlign: 'center',
  },
  moreWaysSection: {
    gap: 12,
  },
  moreWaysTitle: {
    color: '#f8fafc',
    paddingHorizontal: 2,
  },
  shortcutRow: {
    paddingLeft: 2,
    paddingRight: 20,
  },
  shortcutCardWrap: {
    marginRight: 10,
  },
  shortcutCard: {
    maxHeight: 114,
    gap: 4,
  },
  shortcutMediaFrame: {
    height: 68,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#a4b8b2',
    backgroundColor: '#020202',
    overflow: 'hidden',
  },
  shortcutMediaInner: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shortcutCopyBlock: {
    gap: 2,
    paddingHorizontal: 8,
  },
  shortcutHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  shortcutTitle: {
    color: '#f8fafc',
    flex: 1,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '800',
  },
  shortcutSubtitle: {
    color: '#d1d5db',
    fontSize: 10,
    lineHeight: 12,
  },
  shortcutArrowWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  findingScreen: {
    flex: 1,
    backgroundColor: appColors.primary,
    paddingHorizontal:16
  },
  findingTopBar: {
    position: 'absolute',
    top: 0,
    left: 16,
    right: 16,
    zIndex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  findingContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  findingAvatarRing: {
    width: 98,
    height: 98,
    borderRadius: 49,
    borderWidth: 1,
    borderColor: '#3f8483',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  findingAvatarCore: {
    width: 78,
    height: 78,
    borderRadius: 39,
    backgroundColor: '#0b4d50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  findingAvatarLabel: {
    color: '#f8fafc',
    fontWeight: '800',
  },
  findingProgressRow: {
    width: '88%',
    flexDirection: 'row',
    gap: 6,
    marginBottom: 10,
  },
  findingProgressSegment: {
    flex: 1,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#7f9d9e',
    opacity: 0.65,
  },
  findingText: {
    color: '#e6eeee',
    marginBottom: 22,
  },
  findingPulseOuter: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(145, 184, 183, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  findingPulseInner: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(176, 202, 201, 0.38)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  findingPulseCenter: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#aac3be',
  },
  findingCancelButton: {
    marginTop: 28,
    alignSelf: 'stretch',
    borderRadius: 22,
  },
  enRouteScreen: {
    flex: 1,
    backgroundColor: '#121517',
  },
  enRouteTopOverlay: {
    position: 'absolute',
    left: 14,
    right: 14,
    top: 0,
    zIndex: 3,
    gap: 18,
  },
  enRouteTitle: {
    color: '#ffffff',
    fontWeight: '800',
    marginTop: 18,
  },
  enRouteRoutePill: {
    position: 'absolute',
    left: 12,
    right: 78,
    zIndex: 3,
    minHeight: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(248, 250, 252, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(248, 250, 252, 0.18)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    gap: 10,
  },
  enRouteRouteThumb: {
    width: 24,
    height: 24,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.22)',
  },
  enRouteRouteText: {
    color: '#f8fafc',
    fontWeight: '700',
    flex: 1,
  },
  enRouteBottomSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 4,
    backgroundColor: 'rgba(4, 58, 55, 0.95)',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 18,
    paddingHorizontal: 14,
    gap: 18,
  },
  enRouteDriverRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  enRouteDriverIdentity: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  enRouteAvatarWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#0f766e',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  enRouteAvatarImage: {
    width: '100%',
    height: '100%',
  },
  enRouteAvatarLabel: {
    color: '#f8fafc',
    fontWeight: '800',
  },
  enRouteDriverCopy: {
    flex: 1,
    gap: 4,
  },
  enRouteNameRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    flexWrap: 'wrap',
  },
  enRouteDriverName: {
    color: '#ffffff',
    fontWeight: '800',
  },
  enRoutePassengerHandle: {
    color: '#d7ebe8',
    fontWeight: '700',
  },
  enRouteTripTime: {
    color: '#b6cfca',
    fontWeight: '600',
  },
  enRouteActionCluster: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  enRouteActionButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(236, 253, 245, 0.24)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  enRouteSection: {
    gap: 10,
  },
  enRouteSectionTitle: {
    color: '#e7f2ef',
    fontWeight: '700',
  },
  enRouteRouteList: {
    gap: 10,
  },
  enRouteRouteItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  enRouteRouteItemText: {
    flex: 1,
    color: '#d6ebe7',
    lineHeight: 20,
  },
  enRouteFooterActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 2,
  },
  enRouteFooterButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(224, 242, 238, 0.22)',
    backgroundColor: 'rgba(3, 50, 47, 0.78)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 12,
  },
  enRouteFooterButtonSecondary: {
    backgroundColor: 'rgba(9, 67, 63, 0.88)',
  },
  enRouteFooterButtonText: {
    color: '#d7ebe8',
    fontWeight: '700',
  },
  enRoutePickupMarker: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: appColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  enRouteStopMarker: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#4b5563',
    alignItems: 'center',
    justifyContent: 'center',
  },
  enRouteCarMarker: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#21d4b2',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: 'rgba(17, 24, 39, 0.45)',
  },
  driverArriveScreen: {
    flex: 1,
    backgroundColor: '#050608',
  },
  driverArriveTopOverlay: {
    position: 'absolute',
    left: 12,
    right: 12,
    zIndex: 3,
  },
  driverArriveTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  driverArriveStatusPill: {
    flex: 1,
    minHeight: 32,
    borderRadius: 999,
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  driverArriveStatusIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#eaf6f1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverArriveStatusText: {
    color: '#172224',
    // fontWeight: '700',
    flex: 1,
  },
  driverArriveMiniAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#134043',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
  },
  driverArriveMiniAvatarImage: {
    width: '100%',
    height: '100%',
  },
  driverArriveMiniAvatarLabel: {
    color: '#f8fafc',
    fontWeight: '800',
  },
  driverArriveMiniAvatarBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#ef4444',
  },
  driverArriveDestinationWrap: {
    position: 'absolute',
    left: 18,
    right: 56,
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  driverArriveDestinationThumb: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverArriveDestinationText: {
    color: '#f8fafc',
    fontWeight: '700',
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  driverArriveEtaStrip: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 14,
    paddingBottom: 10,
    backgroundColor: appColors.primary,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
  },
  driverArriveEtaText: {
    color: '#f5f8f7',
    fontWeight: '700',
  },
  driverArriveHandle: {
    width: 54,
    height: 5,
    borderRadius: 999,
    alignSelf: 'center',
    backgroundColor: '#a9b4b1',
    marginBottom: 10,
  },
  driverArriveSheetModal: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 3,
    backgroundColor: appColors.primary,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: 'hidden',
  },
  driverArriveSheetBodyContent: {
    flexGrow: 1,
  },
  driverArrivePrimaryPanel: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 12,
  },
  driverArriveVehicleCard: {
    borderWidth: 1,
    borderColor: 'rgba(177, 219, 209, 0.42)',
    borderRadius: 22,
    backgroundColor: 'rgba(8, 58, 54, 0.96)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 64,
  },
  driverArriveVehicleBadge: {
    width: 46,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverArriveSeatBadge: {
    position: 'absolute',
    right: -4,
    bottom: -6,
    minWidth: 20,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#d9dfdf',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  driverArriveSeatBadgeText: {
    color: '#39484c',
    fontWeight: '800',
    fontSize: 10,
    lineHeight: 12,
  },
  driverArriveVehicleMeta: {
    flex: 1,
    gap: 2,
  },
  driverArriveVehicleTitle: {
    color: '#f8fafc',
    fontWeight: '800',
  },
  driverArriveVehicleSubtitle: {
    color: '#9cbdb7',
    fontWeight: '600',
  },
  driverArriveVehiclePrice: {
    color: '#f8fafc',
    fontWeight: '800',
    fontSize: 16,
    lineHeight: 20,
  },
  driverArriveDriverCard: {
    borderWidth: 1,
    borderColor: 'rgba(177, 219, 209, 0.42)',
    borderRadius: 22,
    backgroundColor: 'rgba(8, 58, 54, 0.96)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 64,
  },
  driverArriveDriverMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingBottom: 0,
  },
  driverArriveDriverAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#1d5f63',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'visible',
  },
  driverArriveDriverAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
  driverArriveDriverAvatarLabel: {
    color: '#f8fafc',
    fontWeight: '800',
  },
  driverArriveRatingBadge: {
    position: 'absolute',
    left: -2,
    bottom: -6,
    backgroundColor: '#f4f7ef',
    borderRadius: 999,
    paddingHorizontal: 6,
    minHeight: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverArriveRatingText: {
    color: '#172224',
    fontWeight: '800',
  },
  driverArriveDriverMeta: {
    flex: 1,
    gap: 4,
  },
  driverArriveDriverName: {
    color: '#f8fafc',
    fontWeight: '800',
  },
  driverArriveDriverSubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  driverArriveDriverSubtext: {
    color: '#b7d0cc',
    fontWeight: '600',
  },
  driverArriveActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  driverArriveActionButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(196, 226, 220, 0.28)',
    backgroundColor: 'rgba(255,255,255,0.03)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverArriveAlertBadge: {
    position: 'absolute',
    top: -4,
    right: -3,
    minWidth: 15,
    height: 15,
    borderRadius: 8,
    backgroundColor: '#ef4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  driverArriveAlertBadgeText: {
    color: '#ffffff',
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '800',
  },
  driverArriveRouteCard: {
    borderWidth: 1,
    borderColor: 'rgba(177, 219, 209, 0.42)',
    borderRadius: 18,
    backgroundColor: 'rgba(8, 58, 54, 0.96)',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  driverArriveRouteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 42,
  },
  driverArriveRouteCopy: {
    flex: 1,
    gap: 2,
  },
  driverArriveRouteLabel: {
    color: '#8eb3ab',
    fontWeight: '600',
  },
  driverArriveRouteValue: {
    color: '#f8fafc',
    fontWeight: '700',
  },
  driverArriveRouteDivider: {
    height: 1,
    backgroundColor: 'rgba(197, 226, 220, 0.12)',
    marginVertical: 7,
  },
  driverArriveRouteAction: {
    color: '#9fc0bc',
    fontWeight: '800',
    fontSize: 18,
    lineHeight: 18,
  },
  driverArriveAddStop: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#93bdb7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverArriveAddStopText: {
    color: '#d8eae7',
    fontWeight: '700',
    lineHeight: 12,
  },
  driverArriveDestinationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#e2f1ee',
    marginLeft: 3,
    marginRight: 3,
  },
  driverArriveSectionHeader: {
    marginTop: 2,
  },
  driverArriveSectionTitle: {
    color: '#f8fafc',
    fontWeight: '800',
  },
  driverArrivePaymentCard: {
    borderWidth: 1,
    borderColor: 'rgba(177, 219, 209, 0.42)',
    borderRadius: 22,
    backgroundColor: 'rgba(8, 58, 54, 0.96)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
    minHeight: 56,
  },
  driverArrivePaymentBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(204, 231, 226, 0.22)',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverArrivePaymentCopy: {
    flex: 1,
    gap: 2,
  },
  driverArrivePaymentTitle: {
    color: '#f8fafc',
    fontWeight: '800',
  },
  driverArrivePaymentSubtitle: {
    color: '#c8dddd',
  },
  driverArrivePaymentAction: {
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  driverArrivePaymentActionText: {
    color: '#c8dddd',
    fontWeight: '700',
  },
  driverArriveCancelButton: {
    marginTop: 4,
    alignSelf: 'stretch',
    borderRadius: 22,
  },
  driverArriveMarkerPickup: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: appColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  driverArriveMarkerStop: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#0e2f33',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#ffffff',
  },
  driverArriveMarkerDestination: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#ffffff',
    borderWidth: 3,
    borderColor: appColors.primary,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  topBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  roundButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#4b5563',
    backgroundColor: 'rgba(2, 6, 23, 0.68)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  planPill: {
    minHeight: 42,
    borderRadius: 21,
    backgroundColor: '#ffffff',
    paddingHorizontal: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  planPillText: {
    color: '#0f172a',
  },
  avatarWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: '#4b5563',
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#f8fafc',
  },
  avatarDot: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ef4444',
  },
bottomSheet: {
  position: 'absolute',
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: '#0d1117',          // ← was appColors.primary (green). Now dark neutral.
  borderTopLeftRadius: 24,
  borderTopRightRadius: 24,
  borderTopWidth: 1,
  borderTopColor: '#1e293b',           // ← was #0e7490 (teal). Now subtle slate.
  paddingHorizontal: 14,
  paddingTop: 0,                        // ← was 14. Handle zone provides top spacing now.
  gap: 10,
  // maxHeight removed — height is driven by Animated.Value in PlannerLayout
},
bottomSheetVehicle: {
  backgroundColor: appColors.primary,          // ← was #003f41 (green). Now matches bottomSheet.
  borderTopColor: '#1e2d3d',           // ← was #0f6b6d (teal)
},
  greetingText: {
    color: '#f8fafc',
    textAlign: 'center',
  },
  scheduleChip: {
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#0f766e',
    backgroundColor: 'rgba(2, 23, 23, 0.85)',
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  scheduleChipText: {
    color: '#dbeafe',
  },
  quickPlaceList: {
    gap: 8,
    paddingTop: 2,
    maxHeight: 200,
  },
  quickPlaceItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  quickPlaceIconWrap: {
    marginTop: 2,
    width: 20,
    alignItems: 'center',
  },
  quickPlaceTextWrap: {
    flex: 1,
    gap: 2,
  },
  quickPlaceTitle: {
    color: '#f8fafc',
  },
  quickPlaceSubtitle: {
    color: '#d1d5db',
  },
  footerHint: {
    color: '#cbd5e1',
  },
  routeCard: {
    borderWidth: 1,
    borderColor: '#0f766e',
    borderRadius: 16,
    backgroundColor: 'rgba(1, 49, 52, 0.95)',
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 8,
  },
  routeRow: {
    gap: 4,
  },
  routeLabel: {
    color: '#93c5fd',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  routeValue: {
    color: '#f8fafc',
  },
  routeDivider: {
    height: 1,
    backgroundColor: 'rgba(148, 163, 184, 0.35)',
  },
  vehicleScroll: {
    flexGrow: 0,
  },
  vehicleContent: {
    paddingTop: 2,
  },
  sheetHandle: {
    width: 44,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#97a6a4',
    alignSelf: 'center',
    marginBottom: 10,
  },
  vehicleRouteCard: {
    borderWidth: 1,
    borderColor: '#2e8f8f',
    borderRadius: 18,
    backgroundColor: '#01393b',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 14,
  },
  vehicleRouteTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  vehicleRouteMiddleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 34,
  },
  vehicleRouteBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  vehicleRouteTextWrap: {
    flex: 1,
    gap: 1,
  },
  vehicleRouteLabel: {
    color: '#8ea8a9',
    textTransform: 'none',
  },
  vehicleRoutePrimaryValue: {
    color: '#f5f9f9',
    fontWeight: '700',
  },
  vehicleRouteMiddleText: {
    color: '#eef4f4',
    flex: 1,
  },
  vehicleRoutePlaceholder: {
    color: '#9db6b8',
    fontStyle: 'italic',
  },
  vehicleRouteDivider: {
    height: 1,
    backgroundColor: 'rgba(148, 163, 184, 0.22)',
    marginVertical: 9,
  },
  routeDot: {
    width: 11,
    height: 11,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#e2f0f0',
  },
  routeDestinationIconWrap: {
    width: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  routeDestinationDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#e2f0f0',
  },
  routeActionGhost: {
    padding: 2,
  },
  routeActionCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#94a3b8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  routeActionPlusText: {
    color: '#cfd8e3',
    lineHeight: 14,
  },
  stopPickerCard: {
    borderWidth: 1,
    borderColor: '#2e8f8f',
    borderRadius: 14,
    backgroundColor: '#014244',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
    marginBottom: 10,
  },
  stopPickerTitle: {
    color: '#d8e3e4',
    marginBottom: 2,
  },
  stopPickerItem: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  stopPickerItemTitle: {
    color: '#f8fafc',
  },
  stopPickerItemSubtitle: {
    color: '#b9ccd0',
  },
  sectionHeading: {
    color: '#f8fafc',
    marginBottom: 8,
    fontWeight: '700',
  },
  vehicleList: {
    gap: 12,
    marginBottom: 16,
  },
  vehicleCard: {
    borderWidth: 1,
    borderColor: '#2e8f8f',
    borderRadius: 22,
    backgroundColor: '#014447',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  vehicleCardActive: {
    borderColor: '#5ab2ae',
    backgroundColor: '#1a5558',
  },
  vehicleBadgeWrap: {
    width: 46,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#0d5f62',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehicleBadge: {
    color: '#f8fafc',
    fontSize: 11,
    lineHeight: 14,
  },
  vehicleTextWrap: {
    flex: 1,
    gap: 2,
  },
  vehicleTitle: {
    color: '#f8fafc',
  },
  vehicleSubtitle: {
    color: '#d6e3e3',
  },
  vehiclePrice: {
    color: '#f8fafc',
    fontWeight: '700',
  },
  paymentList: {
    gap: 10,
    marginBottom: 16,
  },
  paymentCard: {
    borderWidth: 1,
    borderColor: '#2e8f8f',
    borderRadius: 20,
    backgroundColor: '#013f42',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  paymentCardActive: {
    borderColor: '#5ab2ae',
    backgroundColor: '#0b4c4f',
  },
  paymentTextWrap: {
    flex: 1,
    gap: 2,
  },
  paymentTitle: {
    color: '#f8fafc',
  },
  paymentSubtitle: {
    color: '#cbd5e1',
  },
  findDriverButton: {
    marginBottom: 4,
    marginTop: 2,
    borderRadius: 24,
    backgroundColor: '#f2f4f5',
    borderColor: '#d5dbe0',
  },
  pressed: {
    opacity: 0.8,
  },
  dragHandleZone: {
  width: '100%',
  paddingTop: 10,
  paddingBottom: 6,
  alignItems: 'center',
},
});
